publishDir = "docs/"

baseURL = "https://strongjz.github.io/louk8cnc-intro-k8s/"
languageCode = "en-us"
disableKinds = ["sitemap", "RSS"]

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true





