publishDir = "docs/"
baseURL = "https://strongjz.github.io/louk8cnc-intro-k8s/"
title = "Introduction to Kubernetes"

theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[reveal_hugo]
theme = "night"
margin = 0.2



