publishDir = "docs/"
baseURL = "/"
languageCode = "en-us"
title = "Introduction to Kubernetes"
theme = "reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "mine"

