publishDir = "docs/"
baseURL = "https://strongjz.github.io/intro-k8/"
languageCode = "en-us"
title = "Introduction to Kubernetes"
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "mine"

