publishDir = "docs/"
baseURL = "https://strongjz.github.io/louk8cnc-intro-k8s"
languageCode = "en-us"
title = "Introduction to Kubernetes"
theme = "learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "mine"

