---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  my.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
---


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        args:
         - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: config-map
          mountPath: /mnt/config-map
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
         exec:
          #Currently probes don't have access to container level env vars so we'll use the bash shell that will
           command:
            - bash
            - "-c"
            - |
            - mysql -u root -p $MYSQL_ROOT_PASSWORD -h 127.0.0.1 -e 'SHOW DATABASES'
         initialDelaySeconds: 5
         periodSeconds: 2
         timeoutSeconds: 1
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-volume-claim
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
